[build]
command = "mkdocs build"
publish = "site/"

[[redirects]]
  from = "/angular/tutorial/*"
  to = "https://angdev.ru/doc/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/angular/*"
  to = "https://angdev.ru/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "/nodejs/tutorial/*"
  to = "https://nodejsdev.ru/doc/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/nodejs/*"
  to = "https://nodejsdev.ru/:splat"
  status = 301
  force = true