[build]
command = "mkdocs build"
publish = "site/"

[[redirects]]
  from = "/angular/tutorial/*"
  to = "https://angdev.ru/doc/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/angular/*"
  to = "https://angdev.ru/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/nodejs/tutorial/*"
  to = "https://nodejsdev.ru/doc/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/nodejs/*"
  to = "https://nodejsdev.ru/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/react/*"
  to = "https://reactdev.ru/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/html/*"
  to = "https://hcdev.ru/html/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/css/flex-guide/*"
  to = "https://hcdev.ru/flex/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/css/grid-guide/*"
  to = "https://hcdev.ru/grid/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/css/*"
  to = "https://hcdev.ru/css/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/typescript/*"
  to = "https://scriptdev.ru/ts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/javascript/canvas/*"
  to = "https://scriptdev.ru/webapi/canvas/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/javascript/garden/*"
  to = "https://scriptdev.ru/js/garden/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/javascript/xhr/*"
  to = "https://scriptdev.ru/webapi/xhr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/javascript/json/*"
  to = "https://scriptdev.ru/json/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/javascript/*"
  to = "https://scriptdev.ru/js/:splat"
  status = 301
  force = true
